name: Update Top Shoes
on: 
  push: 
    branches:
      - master
  schedule:
    - cron:  '0 */24 * * *'
jobs:
  Update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec ruby main.rb
      - name: Commit index html
        run: |
          git config --global user.name 'Arthur Dzieniszewski'
          git config --global user.email 'arthurdzieniszewski@gmail.com'
          git diff index.html | xargs -0 echo | wc -w || (git add index.html && git commit -m "Automated update" && git push --force)
